# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookSearch
  pod "SwiftLint"
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'BookSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
